{
 "title": "LEC",
 "time": { "from": "2022-09-14T15:34:32.781Z", "to": "2022-09-17T04:24:55.406Z" },
 "panels": [
  {
   "title": "WWT Mean Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  temperature\nFROM etwarmwatertankmeasurement\nWHERE\n  $__timeFilter(time_index)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "WWT Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  activepower\nFROM etwarmwatertankmeasurement\nWHERE\n  $__timeFilter(time_index)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "PV Energy Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_index AS \"time\",\n  entity_id AS metric,\n  activepower\nFROM etphotovoltaicmeasurement\nWHERE\n  $__timeFilter(time_index)\nORDER BY 1,2"
    }
   ]
  }
 ]
}